# https://help.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Bump Go'
description: 'Bump the Go compiler version to the most up-to-date release'
author: 'panchoh'
branding:
  icon: 'refresh-cw'
  color: 'blue'
inputs:
  go-version-filepath:
    description: 'Path to the file containing the Go version to build your project'
    required: false
    default: '.github/versions/go'
outputs:
  go-version:
    description: 'Latest current Go version'
runs:
  using: 'node12'
  main: 'dist/index.js'
